server:
  port: 9000

spring:
  application:
    name: oauth
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: mysql
    show-sql: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 28000000
      max-lifetime: 28000000
      maximum-pool-size: 30
  security:
    oauth2:
      authorizationserver:
        issuer: http://auth-server:9000
